"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { Shell } from "@/components/Shell";
import { apiJson, authHeaders } from "@/lib/api";

type Subject={id:string;display_name:string};
type Session={id:string;title:string;movement_template:string;status:string;review_status:string;created_at:string};
type Job={id:string;state:string;stage:string;progress:number};
export default function Sessions() {
  const [sessions,setSessions]=useState<Session[]>([]); const [subjects,setSubjects]=useState<Subject[]>([]); const [job,setJob]=useState<Job|null>(null); const [error,setError]=useState("");
  const load=()=>Promise.all([apiJson<Session[]>("/api/v1/sessions",{headers:authHeaders()}),apiJson<Subject[]>("/api/v1/subjects",{headers:authHeaders()})]).then(([a,b])=>{setSessions(a);setSubjects(b)}).catch((e:Error)=>setError(e.message));
  useEffect(() => { void load(); },[]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=event.currentTarget;const data=new FormData(form);try{const session=await apiJson<Session>("/api/v1/sessions",{method:"POST",headers:authHeaders({"Content-Type":"application/json"}),body:JSON.stringify({subject_id:data.get("subject_id"),title:data.get("title"),movement_template:data.get("movement_template"),processing_configuration:{sample_fps:Number(data.get("sample_fps")||8)}})});const file=data.get("video");if(file instanceof File&&file.size){const upload=new FormData();upload.append("file",file);const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000"}/api/v1/sessions/${session.id}/media`,{method:"POST",headers:authHeaders(),body:upload});const payload=await response.json();if(!response.ok)throw new Error(typeof payload.detail==="string"?payload.detail:payload.detail?.message||"Upload failed");setJob(payload)}form.reset();load()}catch(e){setError((e as Error).message)}}
  return <Shell><div className="eyebrow">Operations</div><h1>Movement sessions</h1><div className="grid" style={{gridTemplateColumns:"minmax(300px,.6fr) minmax(0,1fr)"}}><form className="card stack" onSubmit={create}><h3>Create and upload</h3><label>Subject<select name="subject_id" required><option value="">Select subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select></label><label>Session title<input name="title" required placeholder="Squat baseline" /></label><label>Movement template<select name="movement_template"><option value="squat">Squat</option><option value="bicep_curl">Bicep curl</option><option value="shoulder_raise">Shoulder raise</option><option value="sit_to_stand">Sit to stand</option></select></label><label>Sampled FPS<input name="sample_fps" type="number" min="1" max="30" defaultValue="8" /></label><label>MP4 or MOV<input name="video" type="file" accept="video/mp4,video/quicktime" /></label>{error&&<p className="error">{error}</p>}{job&&<p className="muted">Job {job.state} · {job.stage} · {job.progress}%</p>}<button className="btn" disabled={!subjects.length}>Create session</button></form><div className="card"><table className="table"><thead><tr><th>Session</th><th>Template</th><th>Status</th><th>Review</th></tr></thead><tbody>{sessions.map(session=><tr key={session.id}><td>{session.status==="completed"?<Link href={`/analysis/${session.id}`}>{session.title}</Link>:session.title}</td><td>{session.movement_template}</td><td><span className="badge">{session.status}</span></td><td>{session.review_status}</td></tr>)}</tbody></table>{!sessions.length&&!error&&<p className="muted">No sessions created yet.</p>}</div></div></Shell>;
}
